### ISSUE TITLE
process.on('exit' | 'SIGINT', 'uncaughtException') not working

### ISSUE THREAD

**Issue by kolodny** [kimmobrunfeldt/concurrently#105]
If my js file has any of those callback they won't be invoked when the concurrent master process is killed.

http://stackoverflow.com/a/14032965

**Comment by kolodny** [comment]
To clarify, the callbacks work when I run `node foo.js` file as a standalone, yet don't run when the file is run with `concurrently "node foo.js"`

**Comment by gustavohenke** [comment]
I'll need you to expand this issue a little bit.
- What OS are you using?
- What your `foo.js` file looks like?
- Are you running it simply `concurrently "node foo.js"`, or are there any other flags involved?

**Comment by kolodny** [comment]
I'm using windows, here's an example repo

https://github.com/kolodny/concurrently-example

It works when I run `node foo.js` but doesn't when I run `npm run go`

```
$ node foo.js
exitHandler
exitHandler
clean

$ npm run go

$
```

**Comment by kolodny** [comment]
I'm using MINGW64 from the git-preview binary, not the command line prompt. I just discovered that this issue only manifests when I exit the program with `crtl+c`, when the program exits on it's own accord it prints the messages correctly, see `npm run go-works`

**Comment by gustavohenke** [comment]
Heya @kolodny,
Sorry for this looong delay. I think v4 solved this (at least I tried on a Windows VM, and I couldn't reproduce it anymore).

Please try it and open a new issue otherwise!
