### ISSUE TITLE
Question: Handling SIGTERM

### ISSUE THREAD

**Issue by nrebhun** [kimmobrunfeldt/concurrently#110]
### Background:
I am using concurrently in a bash script to parallelize a number of other supporting scripts.
I am making use of the `--kill-others-on-fail` flag

### Issue:
I'm using concurrently `v3.4.0`, and noticed a behavior I wasn't expecting.
No matter what I tried, the final command would consistently exit `with code null`, while the other tasks would exit `with code 0`.

After reading the FAQ, and reading some of the linked Node documentation, I began to suspect the `pkill` in one of these commands. But I continued tinkering to see what I could find

My initial suspicion was tempered by two things:
1. I could run the exact command outside a script (manually typing the problematic command in my shell) and each parallelized command consistently exits with the expected error code.
2. In all the tinkering I attempted (including re-ordering the commands to isolate the problem) `pkill` was not always the last command, yet the last command consistently reported a `null` exit code.

Finally, I broke my own code apart and took the `pkill` out of the set of parallelized tasks in the script... and it all worked perfectly.

### Wrapping Up:
So... perhaps this is expected behavior. Clearly something like this come up before, because the only item in the FAQ section pointed me in the right direction. But it still left me with a couple of questions. 

Most notably:
1. Why wasn't concurrently correctly identifying the problematic command, always faulting the final command, rather than the command which issued the **SIGTERM**?
2. Why was concurrently behaving as expected when run manually, but not when part of a script?

Thanks for any clarity/assistance that can be provided.

**Comment by dziamid** [comment]
That's confusing me as well. 

With `&` operator:
`npm run start:test & cypress run`
exit code is 0

With concurrenly:
`concurrently -k "npm run start:test" "cypress run"`
exit code is 1 and the output is like this:
```
...
[1] cypress run exited with code 0
--> Sending SIGTERM to other processes..
[0] npm run start:test exited with code null

```

**Comment by berlin-sky** [comment]
We are facing the same issue. Does anyone know how to overcome this? We do not need a ```null``` exit status

**Comment by nrebhun** [comment]
My solution was to remove the offending command from parallelization. That is, part of the original set of parallelized tasks involved a process which **received** a ’SIGTERM’.

The signal was also issued **during** the parallelization, but I suspect that was not the problem.

When I figured this out, I moved the code which issued a ’SIGTERM’ signal outside of the set of parallelized processes, so that no process received that signal while concurrently was keeping an eye on things, and I think **this** is why my solution worked.

**Comment by gustavohenke** [comment]
Hello guys. I'm sorry for taking this long to reply.
Any commands that are killed via signals will exit with code `null`; this is Node's behaviour and we can't change it. Perhaps we could log the right thing instead.

**Comment by berlin-sky** [comment]
Thanks @gustavohenke.

**Comment by gustavohenke** [comment]
Since this issue saw no further comments, I'm closing it.
Let me know in case you think we still can reach consensus, so I can reopen it.

**Comment by peterjwest** [comment]
So, in the case a process exits with 0, and then concurrently terminates the other processes which exit `with code null`, should the exit code of concurrently be 0?

It seems to be non-zero for me, which is breaking my test suite.

**Comment by gustavohenke** [comment]
@peterjwest you can control such behaviour with `--success` arg.

**Comment by peterjwest** [comment]
Awesome, thanks!
