### ISSUE TITLE
direct stdin to a process

### ISSUE THREAD

**Issue by kosmotaur** [kimmobrunfeldt/concurrently#115]
Typical setup for me is having concurrently run nodemon, for which you can trigger a restart by typing `rs` in your terminal. I presume concurrently is ignoring stdin?

**Comment by gustavohenke** [comment]
Yes, we are currently doing nothing to the `stdin` pipe of the child processes.
If you use `--raw`, however, `stdin` will work.

**Comment by kosmotaur** [comment]
brilliant, that worked, thanks!

**Comment by gustavohenke** [comment]
@rotexhawk it's not a nodemon flag, it's a concurrently one.

Also make sure to check #128, it will bring stdin handling.

**Comment by rotexhawk** [comment]
Awesome. Thanks for clarifying it. Hopefully #128 will be merged soon.
