### ISSUE TITLE
Concurrently runs only the first task

### ISSUE THREAD

**Issue by CamiloTerevinto** [kimmobrunfeldt/concurrently#119]
_Question from [StackOverflow](https://stackoverflow.com/questions/45645046/concurrently-runs-only-the-first-task), relevant details below_

The tutorial I was following shows this package.json:

```
"scripts": {
  "start": "node node_modules/react-native/local-cli/cli.js start",
  "tsc": "tsc",
  "clean": "rimraf artifacts",
  "build": "npm run clean && npm run tsc --",
  "lint": "tslint src/**/*.ts",
  "watch": "npm run build -- -w",
  "start:android": "npm run build && concurrently -r \"react-native run-android\" \"npm run watch\""
},
```
But, when I run start:android it only gets to run react-native run-android after the build, it never runs npm run watch. I have not been able to find a lot of documentation around concurrently, but the tutorial explains it allows you to run multiple tasks in parallel.

If I reverse the order of the concurrently tasks, watch is ran but run-android is not, so that doesn't solve the issue either.

I am using the Visual Studio Code's Terminal (Powershell), but the same happens when I use a norma CMD (Windows)

- "concurrently": "^3.5.0"
- npm -v 5.3.0
- node -v v8.2.1

**Comment by jstrother** [comment]
Also having this issue.  Even the most recent version (3.6.0) only runs first task in line.  I really need a reliable way to run multiple tasks in my npm scripts.

**Comment by kingluddite** [comment]
`$ npm run dev` would only run Express server and not React server
  - I experiences this on 3 different computers and just adding this as it may help others
  - My fix is to revert to an older version of concurrently with `$ npm i concurrently@3.6.0` and then install the latest version with `$ npm i concurently@latest`. That seemed to jump start it to work again

I am running Express and React and here are my scripts

package.json

```
// more code
  "scripts": {
    "precommit": "pretty-quick --staged",
    "server": "nodemon server.js",
    "client": "cd client && npm start",
    "dev": "concurrently --names \"server,client\" \"npm run server --silent\" \"npm run client --silent\""
  },
// more code
```

**Comment by gustavohenke** [comment]
Thanks @kingluddite, so you no longer have issues while using v4?

**Comment by kingluddite** [comment]
Correct. And I haven't been able to replicate it again on another computer.

**Comment by jaredStevens** [comment]
@kingluddite In your `scripts` above you have `"client": "cd client && npm start"` check your `package.json` in your client folder and make sure the `start` script exists.  I have to change `"client": "cd client && npm start"` to => `"client": "cd client && npm serve"`... once I did that it worked perfectly.

**Comment by kingluddite** [comment]
@jaredStevens Thank you!
