### ISSUE TITLE
Disable prefix

### ISSUE THREAD

**Issue by OmgImAlexis** [kimmobrunfeldt/concurrently#123]
Is there any way to disable the prefix completely?

**Comment by perry-mitchell** [comment]
Isn't `-r` or `--raw` what you're looking for? For instance, my tests use concurrently.. using regular flags:

![image](https://user-images.githubusercontent.com/3869469/32046053-951297a0-ba4a-11e7-9fdd-dcc6b0098ba2.png)

And with `--raw`:

![image](https://user-images.githubusercontent.com/3869469/32046089-ae0ce01c-ba4a-11e7-9de5-698230f1d82a.png)

**Comment by PowerSupply** [comment]
I would expect:

`--prefix none`

...to not print any prefix, bu instead it prints an empty prefix for every line:

`[]`

**Comment by gustavohenke** [comment]
Hey @PowerSupply, your suggestion makes sense.
I'm labelling this issue as an enhancement for the next version!

**Comment by rotemdan** [comment]
This feature is essential to allow the standard VSCode problem matchers to work correctly (which may apply to other editors as well), see an example in this issue:
https://github.com/Microsoft/vscode/issues/50982

For instance to run multiple TypeScript watchers at the same time:

`tasks.json`:
```json
...
		"command": "concurrently",
		"args": [
			"\"tsc --project A --watch\"",
			"\"tsc --project B --watch\"",
			"\"tsc --project C --watch\"",
		],
...
```
Right now I've resorted to the primitive/possibly broken solution of [commenting out this line in `main.js`](https://github.com/kimmobrunfeldt/concurrently/blob/c8bbe5523e2935c5b709d5c87504abc29ad7c617/src/main.js#L363)
And replacing it with:
```
console.log(event.data.toString());
```

I can definitely try to make a pull request for a more proper solution (#131 seems to have been abandoned - which is very unfortunate), but I'm afraid I don't have the time to write tests etc. at the moment.

**Comment by rotemdan** [comment]
I would also suggest to a consider a `--no-prefix` flag as an alternative as it wouldn't be a breaking change and seems easier to implement. Right now I simply don't have the time to go through the code and figure out what needs to be done, but it doesn't seem very hard.

**Comment by gustavohenke** [comment]
@rotemdan that's fine, a new major version is underway, aiming at easier maintenance time for us and lower issue turnaround time, so it could _finally_ include this change.
Any PR open today is going to be outdated very soon.

**Comment by rotemdan** [comment]
@gustavohenke That's great news! Actually I'm basically done with the PR (which includes a test I adapted from the previous PR) but I'm getting strange errors in the tests. I keep getting:
```
memo.replace is not a function
```
Seems like the reason is adding the flag iself and not the code. Something unexpected in the way it is interpreted by `commander` maybe:
```js
       .option(
           '--no-prefix',
           'suppress the display of prefixes in log messages.\n'
       )
```
Maybe it sets `prefix` to `false` by default just by having the flag?
(this might help you if you come across it in the future)
