### ISSUE TITLE
[Feature Request] Set a delay between commands

### ISSUE THREAD

**Issue by HauntedSmores** [kimmobrunfeldt/concurrently#124]
I would like to start by saying that this is a great library and has proven very useful. Just came across an instance where I needed to delay the start of a particular command.

For context Im working on a Shopify theme and am using concurrently to run `webpack --watch` and `theme watch` side-by-side. The problem is that I dont want themekit to watch until the first webpack build has run. I would only need a simple delay to make that happen.

**Comment by PeterKottas** [comment]
I think that's not the best approach. Take a look at this, it wait-on appears to be much more reliable approach. Problem with delay would be how long you want to delay to ensure the files were created.

**Comment by gustavohenke** [comment]
Yep. [wait-on](https://www.npmjs.com/package/wait-on) is way more robust.

Thanks for the hint @PeterKottas, I use it at work and didn't even remember 😄

**Comment by joshuapinter** [comment]
For those looking for how to implement this, look at https://github.com/kimmobrunfeldt/concurrently/issues/65.

The short answer is: 

```
npm install --save-dev wait-on
```

And then just prefix your command with something to wait for, like: 

```
"app": "wait-on http://localhost:3000/ && node app.js"
```
