### ISSUE TITLE
node ./express-mock.js exited with code null  Using --success option

### ISSUE THREAD

**Issue by megamindbrian** [kimmobrunfeldt/concurrently#125]
here's my command in package.json:

```
   "test": "concurrently --kill-others --success last \"node ./express-mock.js\" \"mocha **/*.spec.js\"",

```

When I run I get a passing mocha test but an error ` node ./express-mock.js exited with code null`

here is how I tried to find help with the issue:
https://www.google.com/search?q=concurrently+success++node+express+exited+with+code+null

**Comment by 7agustibm** [comment]
Try this:
```
   "test": "concurrently --kill-others --success last \"mocha **/*.spec.js\" \"node ./express-mock.js\"",
```

I have had the same problem and if you change the order, it should work correctly.

**Comment by utatti** [comment]
I had the same problem and @7agustibm 's answer actually works!

For me, the problem seems like only happening in Ubuntu. In macOS, `-s last` also works with no problem.

**Comment by gustavohenke** [comment]
Thanks for helping each other, folks!
