### ISSUE TITLE
Way to input

### ISSUE THREAD

**Issue by DmitryGG** [kimmobrunfeldt/concurrently#136]
Is there are ways to input to one running command while this command and another commands which running with concurrently can continue output?

For example:
```
concurently \"firebase experimental:functions:shell\" and \"tsc --watch\"
```
`firebase experimental:functions:shell` can output and take an input, `tsc --watch` only output.

**Comment by gustavohenke** [comment]
Yes @DmitryGG, since v3.6.0 you can do this.
By default all input goes to the first process, but you can control this with `--default-input-target` and by prefixing the input with the index/name: 

```
concurently "tsc --watch" "firebase experimental:functions:shell"
1:someinput
```

For more info, please refer to `concurrently --help`.
