### ISSUE TITLE
Allow user input for a specified process

### ISSUE THREAD

**Issue by SpencerKaiser** [kimmobrunfeldt/concurrently#143]
I love using concurrently but I don't see any support for interacting with a process running with it. For example, I have concurrently setup to run two processes:
1. Watch and build my TypeScript files and compile them to JS when something changes
2. Watch my. `dist` directory and restart the app when changes occur

`2.` is a CLI which prompts the user for input and when I run `concurrently` with the two processes above, however, user input is not sent to the CLI instance so I have to start the app in a separate terminal tab to actually interact with it.

It would be great if support were added to handle this scenario! Thank you!

**Comment by gustavohenke** [comment]
concurrently has been capable of doing this since v3.6.0.
By default all input goes to the first process, but you can control this with `--default-input-target` and by prefixing the input with the index/name: 

```
concurently "tsc --watch" "nodemon"
1:rs
```

For more info, please refer to `concurrently --help`.

**Comment by SpencerKaiser** [comment]
@gustavohenke that's exactly what I needed! Thank you for the help and thanks for the awesome tool!

**Comment by adil-waqar** [comment]
Can I get a little more help on this? I am taking input from stdin, but I cant seem to type anything into console. What's the correct usage for this `--default-input-target` flag?

**Comment by rodrigogsn** [comment]
I've just added `--handle-input` to my script and it worked. I assume it's because the process I need to handle was the first one.

```
"start": "concurrently --kill-others --handle-input \"cd theme && vtex link\" \"gulp watch\" -n \"vtex,gulp\""```
