### ISSUE TITLE
Upgrade Chalk

### ISSUE THREAD

**Issue by jeremejevs** [kimmobrunfeldt/concurrently#146]
Current version - `0.5.1` - uses `supports-color` version `0.2.0`, which, in turn, doesn't check the `FORCE_COLOR` environment variable, so it isn't possible to force colored output of `concurrently` itself without passing it a `--color` flag directly, which is not very ergonomic.

**Comment by gustavohenke** [comment]
Thanks for the heads up! 😅

**Comment by jeremejevs** [comment]
Thanks for making this neat util! :slightly_smiling_face:

**Comment by gustavohenke** [comment]
Released in v3.6.0!
