### ISSUE TITLE
Stdin support causing possible regression in 3.6.0

### ISSUE THREAD

**Issue by voxpelli** [kimmobrunfeldt/concurrently#147]
It looks like we are sometimes struck by a regression in 3.6.0, probably caused by #128, where we probably have been running `concurrently` in a place where it has received data on stdin, data that it has previously ignored.

That data seems to now be parsed, looking for `:` characters, and if one is found it's expected to be the position or name of the process to forward that input to and otherwise it's forwarded to the default process.

Previously none of that happened – no forwarding of stdin and no parsing of the stdin data. Forwarding such data as a default could therefore be considered a breaking change that requires a new major version and if released as a minor version, as now, it needs to be put behind a flag (like `--forward-stdin`).

Now that it has been released the most important thing is to make it work though.

I see two issues that needs fixing:

1. There's an exception that we're sometimes encountering:

```
TypeError: Cannot read property 'write' of null
    at Socket.process.stdin.on (<project-path>/node_modules/concurrently/src/main.js:306:26)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onread (net.js:581:20)
```

This could be silenced by changing `if (target) {` to `if (target && target.stdin) {` on line `306`in:

https://github.com/kimmobrunfeldt/concurrently/blob/b4574e1b76a86410ad2b7cb14ae8f0c6c3a314b3/src/main.js#L304-L309

2. Forwarding stdin by default to the first process and, in the case of `:`-characters in the stdin, to whatever that resolves to, can break current setups and should either an opt-in or an opt-out so that one can easily fix setups that were working before, but isn't working now.

**Comment by wintercounter** [comment]
Same issue here. I have to explicit define `--default-input-target` to work at least for the default one.

**Comment by gustavohenke** [comment]
Hey folks,
I'm so sorry for the oversight on detecting these kinds of problems! It should really have been a major release.

@voxpelli: you seem to have some good context of the problem, are you up for fixing this? I might not be so free any time soon.

@wintercounter: the [Node.js docs](http://devdocs.io/node/child_process#child_process_subprocess_stdin) states that anything other than `stdio: 'pipe'` would cause the I/O objects to be null.
So processes spawned by concurrently are likely inheriting this from the parent.
For you it _could be_ as easy as changing the `stdio` option of your `spawn` call (note the emphasis).

**Comment by voxpelli** [comment]
@gustavohenke Sure, I can try to find some time for it. Which of the mentioned solution would you prefer? A new opt-out for stdin or changing it to an opt-in?

**Comment by wintercounter** [comment]
@voxpelli Just to have something topic related here :)
```js
if (target) {
    if (target.stdin) {
        // write
    }
}
```
With `target && target.stdin` it'll still log error when it shouldn't.

**Comment by voxpelli** [comment]
I'll try to look at it asap after my deadline today 👍

**Comment by hyperknot** [comment]
I'm having problems with `target.stdin.write(line): Cannot read property 'write' of null` as well on 3.6.1. What was the latest stable version without this problem?

**Comment by gustavohenke** [comment]
v3.5.0 had no support for stdin, if that's fine for you 🙂

**Comment by hyperknot** [comment]
Thanks, 3.5.x works perfectly.

**Comment by gustavohenke** [comment]
Hiya folks! [`v4.0.0` is out with a breaking change relating to this!](https://github.com/kimmobrunfeldt/concurrently/releases/tag/v4.0.0) 🚢 
You know have to specify `--handle-input` in order to opt into the input handling feature.
