### ISSUE TITLE
swallowing gulp errors

### ISSUE THREAD

**Issue by reintroducing** [kimmobrunfeldt/concurrently#149]
I am using concurrently and one of the tasks it runs is gulp, which in turn runs a sass and js linter (Sasslint and ESLint respectively). If a lint error is reported by either of those, concurrently swallows it and we're not getting that output in the terminal that we'd normally see if we ran Gulp directly.

I tried adding `--raw` but that did not work. What am I missing here? Appreciate any help you can offer.

**Comment by reintroducing** [comment]
Sure, give me a few days, I'm currently out of town for work. Please don't close the issue in the meantime, I will definitely do that as this is holding us up from using concurrently effectively so i'd really love to get it solved.

**Comment by reintroducing** [comment]
@gustavohenke So I finally got some time to put together a small reproducible project which immediately made me realize that the error was not in concurrently at all and I was able to get everything working as expected. Apologies for the noise but that was a helpful exercise to finally help me track this down. Many thanks.

**Comment by gustavohenke** [comment]
No worries, glad you found the root of your problem!
