### ISSUE TITLE
Custom prefix feature doesn't work

### ISSUE THREAD

**Issue by AlaDouagi** [kimmobrunfeldt/concurrently#152]
Whenever I run this command:
```bash
concurrently "docker-compose up" "nodemon src/"
```
I get a basic output with the process _default index_
![process index](https://user-images.githubusercontent.com/19997619/43005875-0ddb4228-8c2c-11e8-9372-14b5ddb3ad6f.png)

But if I specify a *custom prefix* like in this [line](https://github.com/kimmobrunfeldt/concurrently/blame/master/README.md#L164) of README.md, I got no prefix at all, even the process index disappears.
So after running this command:
```bash
concurrently --prefix "{time}-{pid}" "docker-compose up" "nodemon src/"
```
I get this output as I described
![no prefix](https://user-images.githubusercontent.com/19997619/43006302-406d8e02-8c2d-11e8-8c33-54a2d211fc55.png)

I'm using Node v8.11.3 on Linux Debian.

I don't know if this is a bug or I'm doing something wrong?

**Comment by AlaDouagi** [comment]
@gustavohenke if it's a bug as you labeled this issue; why did you close it?

**Comment by AlaDouagi** [comment]
Oh. thanks @gustavohenke

**Comment by gustavohenke** [comment]
v3.6.1 published to npm with the fix.
