### ISSUE TITLE
Question:Change colors of output with JS Karma/Mocha 

### ISSUE THREAD

**Issue by chrisdel101** [kimmobrunfeldt/concurrently#156]

**Comment by gustavohenke** [comment]
Not possible.
Do you want to have all the output plainly written using some colour?

I imagine processes can still override colours on their own.

**Comment by chrisdel101** [comment]
I am not sure how I posted this question without any input.  The output in mocha is different that the terminal default. Running concurrently it is all white, and hard to distinguish.
