### ISSUE TITLE
Pipe list of commands for concurrently to run 

### ISSUE THREAD

**Issue by drschwabe** [kimmobrunfeldt/concurrently#161]
Hey there, wondering how to feed concurrently a list of (dynamic) commands to run? 

For example, I have a directory of scripts I would like to run watch on all at once; I understand conccurently has wildcards but thing is I don't want to maintain package.json everytime I add a new script.  Ie- I want to feed concurrently a dynamic list. 

So I wrote a small script called `watch-scripts` to loop over each script (each within their own dir) ...
```
var fs = require('fs') 
var dirs = fs.readdirSync('./scripts')
var commandToOutput = ''
dirs.forEach((dir) => {
  commandToOutput = commandToOutput + ' "cd scripts/' + dir + '; npm run watch"'
})
console.log(commandToOutput)
```

and then tried piping output to concurrently in my package.json like so: 
```
 "watch-scripts" : "node watch-scripts.js | concurrently --raw"
```
Concurrently doesn't seem to do anything with console/echo'ed input like this; perhaps there is something I am missing - or a better technique to try ?

**Comment by gustavohenke** [comment]
Hello @drschwabe,
Unfortunately there is some conflict with concurrently sending input to the child commands. I'm accepting ideas on how to solve this conflict, though.

Also, concurrently v4 will feature a programmatic API, so you will be able to do what you want just fine.

**Comment by drschwabe** [comment]
Ok np!  In the meantime I might try a more elaborate batch script for my particular use-case or just tough it out by manually entering each script to package.json

Looking forward to v4!  Will close this for now - and will keep an eye out for when your v4 branch is available ;)

**Comment by gustavohenke** [comment]
Ah, v4 is out already! Sorry I didn't let you know.
