### ISSUE TITLE
Using single quotes instead of escaping double quotes

### ISSUE THREAD

**Issue by thasmo** [kimmobrunfeldt/concurrently#167]
Would it be possible to add support for single quotes in addition to escaped double quotes?

`"concurrently 'tsc --watch' 'rollup --config --watch'"` vs `"concurrently \"tsc --watch\" \"rollup --config --watch\""`

**Comment by gustavohenke** [comment]
Probably not.
This is likely an OS/Node.js limitation -- you can use single quotes on Unix, but not on Windows --, and the CLI framework we use seems to respect that.
