### ISSUE TITLE
Feature Request : Allow configuring number of parallel jobs

### ISSUE THREAD

**Issue by abdulkareemnalband** [kimmobrunfeldt/concurrently#175]
## Feature Request

Limit number of parallel jobs to configurable option  like [`make`](https://linux.die.net/man/1/make)'s --jobs/-j option

## Expected Behavior 
There should be an option to configure number of parallel jobs

## Rationale
Running number of jobs more than cpu threads some times can can increase the amount of time required for jobs

**Comment by gustavohenke** [comment]
Thanks for the request, @abdulkareemnalband! It sounds like a reasonable one 👍

**Comment by mtford90** [comment]
Plus one to this - I had to search for a different solution after having crashed my computer a couple times - ideally i'd want to match the num. cpu cores.

**Comment by gustavohenke** [comment]
Duplicate of #159

**Comment by gustavohenke** [comment]
Published [`v5.2.0`](https://github.com/kimmobrunfeldt/concurrently/releases/tag/v5.2.0) with a `--max-processes` flag 🚢
