### ISSUE TITLE
`--success last` not working

### ISSUE THREAD

**Issue by ChrisBAshton** [kimmobrunfeldt/concurrently#177]
Using the following command:

```
concurrently --success last "npm run server" "npm run test"
```

`npm run server` starts the application server.
`npm run test` runs tests against the application.

**Expectation**
When the tests pass in `npm run test`, I expect the `--success` flag to treat the overall `concurrently` command as a success, and to exit the server.

**Observed behaviour**
The test process exits with a 0 code - but the overall `concurrently` command continues to hang (it doesn't kill the server).

NB: I've tried various ways of re-writing the flag (e.g. `--success="last"`, `success "last"` etc), as well as moving the flag to the end of the command. For what it's worth, I've also tried re-ordering the command and passing `--success first` instead, but this also fails to exit the server.

Is this down to me misunderstanding what `--success` does, or not implementing `--success` properly in the command, or is this a bug with the `--success` flag?

**Comment by gustavohenke** [comment]
`--success last` is just telling that the last process to exit will determine if concurrently itself will exit with code `0` or not.
It doesn't stop any running processes.

What you probably want to do is to pass the flag `--kill-others --success first`, so the test exits first (killing the server process) and its exit code is concurrently's.

**Comment by ChrisBAshton** [comment]
Thanks - that's what I wanted.

**Comment by Szymon-dziewonski** [comment]
@gustavohenke Thank you, this is what I was looking for <3
