### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by Sicria** [kimmobrunfeldt/concurrently#19]
Is it possible to have a timestamp before the console lines.

So something like this.
```
[2015-12-20 21:09:52] [1] Executing script: start-dev
```

**Comment by kimmobrunfeldt** [comment]
I'm ready to accept a PR if someone implements this. Don't have time to do it currently.

**Comment by danibram** [comment]
I added the functionality in this pull request: #24

**Comment by kimmobrunfeldt** [comment]
This is possible in the new release: https://github.com/kimmobrunfeldt/concurrently/releases/tag/2.0.0

Your example can be achieved with custom prefix:
`concurrently --prefix "[{time}] [{index}]" "start-dev" ".."`
