### ISSUE TITLE
[question] How --handle-input can be used from CLI?

### ISSUE THREAD

**Issue by Andarist** [kimmobrunfeldt/concurrently#191]
I struggle with setting this up, I have such script:
```
"dev": "concurrently --handle-input \"npm run test -- --watch\" \"npm run build -- -w\" --kill-others-on-fail"
```
and I want to forward every input to the test script - so I thought it would be as easy to type something and that it would work.

After looking into the source code I see that InputHandler actually listens to data event on the inputStream, but it's never triggered.

**Comment by gustavohenke** [comment]
I assume you have eventually fixed your issue then?

**Comment by Andarist** [comment]
I actually went different route slightly (havent used concurrently for this). It wasnt working for me because my test script (jest) was running with raw mode stdin and concurrently didnt support that.

**Comment by luckylooke** [comment]
@Andarist it seems I hit [same issue in very similar environment](https://stackoverflow.com/questions/73458426/concurrently-handle-input-does-not-work-as-expected), can you please provide your solution? 

@gustavohenke is there a solution to use concurrently for this usecase?

Many thanks for any advise 🙏🙏🙏

**Comment by luckylooke** [comment]
Actually with `--raw` option it works as expected 😍👍 

My final script:
```json
"test:unit": "concurrently --raw --kill-others --handle-input --names test,build \"vitest --environment jsdom\" \"vite build --watch\"",
```

Thank you @paescuj 🙏

**Comment by paescuj** [comment]
> Actually with `--raw` option it works as expected 😍👍
> 
> My final script:
> 
> ```json
> "test:unit": "concurrently --raw --kill-others --handle-input --names test,build \"vitest --environment jsdom\" \"vite build --watch\"",
> ```
> 
> Thank you @paescuj 🙏

You're welcome! Glad I could help 😃
