### ISSUE TITLE
Concurrently doesn't terminate child processes on SIGHUP signal

### ISSUE THREAD

**Issue by leo-buneev** [kimmobrunfeldt/concurrently#193]
When you start concurrently in a terminal, and then kill this terminal instance, child processes aren't get terminated.

From my understanding the reason for it - when terminal is killed process inside this terminal recieves SIGHUP instead of SIGINT or SIGTERM.

Would be good if concurrently can handle SIGHUP too and pass this signal to child processes.

**Comment by gustavohenke** [comment]
👍 SGTM. Happy to get PRs for this!

**Comment by gustavohenke** [comment]
Landed on [`v5.0.0`](https://github.com/kimmobrunfeldt/concurrently/releases/tag/v5.0.0)!
