### ISSUE TITLE
Any way to run concurrently but sequentially?

### ISSUE THREAD

**Issue by jayarjo** [kimmobrunfeldt/concurrently#199]
Any way to run concurrently but sequentially? Retaining the order of commands that is, so that second one doesn't start before first one doesn't land into the watch mode.

Babel for example processes all files before it launches the watch mode. So if another command depends on the transpiled files to be already present, it might fail if Babel didn't manage to finish it's preliminary transpilation operation.

**Comment by Nox-404** [comment]
You can use a package like `wait-on` to make your other command wait for a file or http to be present
https://www.npmjs.com/package/wait-on

**Comment by Nox-404** [comment]
```
"scripts": {
    "build": "tsc",
    "e2e": "concurrently -k npm:e2e:wait-and-run npm:e2e:server",
    "e2e:server": "npm run build && nyc node dist/src",
    "e2e:wait": "wait-on -l -i 1000 http-get://127.0.0.1:3000/api/health",
    "e2e:newman": "newman run -e specs/environment.json specs/campaign.json",
    "e2e:wait-and-run": "npm run e2e:wait && npm run e2e:newman"
  },
```

Something like that

**Comment by gustavohenke** [comment]
Yes, what @Nox-404 said.
There's no deterministic way that could be embedded into concurrently to tell if a program is "in watch mode".
