### ISSUE TITLE
Clean messy output

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/concurrently#2]
Example of messy output:

```
[1] ./node_modules/watchify/node_modules/through2/node_modules/xtend
[1] ./node_modules/watchify/no

... Lot of output of [0] process ...

[1] de_modules/through2/node_modules/xtend/.jshintrc
```

Outputs should be grouped so that lines wouldn't be cut.

**Comment by elliottsj** [comment]
:+1: Also seeing messy output

**Comment by aecz** [comment]
I rewrote the `logWithPrefix` function to have a cleaner output (almost the same as without concurrently).
Basically, you need to have `lastChar` variable available outside of the function so you know if you are a at the beginning of a new line or not. This covers most of the edge cases when the `stdout` moves the cursor or delete characters.

```javascript
var lastChar;

function logWithPrefix(prefix, prefixColor, text, color) {
   
     if (config.raw) {  
        process.stdout.write(text);
        return;
    }
    
    text = text.replace(/\u2026/g,'...'); // Ellipsis

    var lines = text.split('\n');
    // Do not bgColor trailing space
    var coloredPrefix = colorText(prefix.replace(/ $/, ''), prefixColor) + ' ';
    var paddedLines = _.map(lines, function(line, index) {
        var coloredLine = color ? colorText(line, color) : line;
        if (index !== 0 && index !== (lines.length - 1)) {
            coloredLine = coloredPrefix + coloredLine;
        }
        return coloredLine;
    });
    
    if (!lastChar || lastChar == '\n' ){
        process.stdout.write(coloredPrefix);
    }

    lastChar = text[text.length - 1];         
       
    process.stdout.write(paddedLines.join('\n'));    
}
```

**Comment by JuanCaicedo** [comment]
Has this been fixed, perhaps by the move to node v4? I'm running the latest version of `concurrently` on node v4.4.5 and don't experience this.

@kimmobrunfeldt @elliottsj what commands were you running? Just wondering if I can repro

**Comment by aecz** [comment]
Sorry, didnt link the PR. Here it is #70 
I included a repo and command lines to reproduce.

**Comment by gustavohenke** [comment]
Sorry for the delay on releasing this, folks! Check v3.5.1 🚢
