### ISSUE TITLE
Support `cwd` for commands

### ISSUE THREAD

**Issue by peterp** [kimmobrunfeldt/concurrently#216]
Right now I need to run a command in a specific directory like this (when using concurrently programatically.)

`cd path/to/directory &&  run-command.sh`

This is fine, but becomes problematic when my directory contains spaces. It would be great if we had support for specifying a current working directory.

**Comment by thdk** [comment]
@peterp  long time ago, but if you would still need it, you could see #246

**Comment by thdk** [comment]
@peterp did you try out my PR? Maybe your feedback / review can help @kimmobrunfeldt to decide if it can safely be merged and released or not. We are waiting for this feature as well. But don't want to rush it too much. I hope this 'ping' is ok ;)

**Comment by gustavohenke** [comment]
Out in v6.0.0!
