### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by Toilal** [kimmobrunfeldt/concurrently#22]
I need to start 2 commands in 2 distinct working directories. Is it possible with this tool ?

**Comment by kimmobrunfeldt** [comment]
That's not possible currently. As a workaround you could create two shell scripts which make sure they are running in given directory

**Comment by Toilal** [comment]
Thanks for quick answer.

I finally wrote something like this in package.json:

```
  "scripts": {
    "test": "gulp test",
    "all": "concurrent 'npm run bilan' 'npm run gp2'",
    "bilan": "gulp serve",
    "gp2": "cd ../third-party/gp2/gp2-webapp && gulp serve"
  },
```

And running `npm run all` just run both commands. Thanks !
