### ISSUE TITLE
[QUESTION] Is this real multithreading then?

### ISSUE THREAD

**Issue by JoeSchr** [kimmobrunfeldt/concurrently#224]
Under the hood, it's just like starting several node.js processes in different terminals instead of running a single one node.js on only one processor right?

**Comment by kimmobrunfeldt** [comment]
Unless something has changed in the process spawning lately, it spawns new processes to run the commands.

**Comment by gustavohenke** [comment]
Yeah, it didn't change.
You could choose to run any executable, not only node.js ones with concurrently.
