### ISSUE TITLE
Allow spaces at prefix start/end

### ISSUE THREAD

**Issue by McAllaster** [kimmobrunfeldt/concurrently#227]
Custom prefixes currently strip any space, tab, newline, or other white-space characters at the beginning and end of their supplied content.

This seems to be a bug, as I would expect the supplied value to persist unmodified.

Example input:
```shell
concurrently -p '\u0020{name}\u0020' -n foo,bar 'echo "foo"' 'echo "bar"'
```
Current output:
```shell
foo foo
bar bar
```
Desired output:
```shell
 foo  foo
 bar  bar
```

**Comment by gustavohenke** [comment]
Fair 👍 tagged as a bug, should be easy enough for newcomers to take a stab.
