### ISSUE TITLE
colors and --raw mode

### ISSUE THREAD

**Issue by Toilal** [kimmobrunfeldt/concurrently#23]
I run 2 gulp scripts that stream logs in colors, but want to remove the [0] and [1] from output.

Problem is that when using ```--raw``` mode, colors are also removed from output.

I think it would make more sense to keep colors from underlying process, and allow to disable them only when using both ```--no-color``` option.

**Comment by Toilal** [comment]
In fact, it seems concurrently drops colors from underlying process.

**Comment by Toilal** [comment]
same issue with `-p none`

**Comment by kimmobrunfeldt** [comment]
This is the same issue as this: https://github.com/kimmobrunfeldt/concurrently/issues/8

It's embarrassing that it has been around for a year now. It is a bug, but I haven't looked in to it.

**Comment by Toilal** [comment]
Sorry, i close this one then !

**Comment by kimmobrunfeldt** [comment]
Fix for this is released: https://github.com/kimmobrunfeldt/concurrently/releases/tag/2.0.0

You need to use --raw mode to get colors working.
