### ISSUE TITLE
Concurrently started crashing with spawn cmd.exe ENOENT code -4058

### ISSUE THREAD

**Issue by looeee** [kimmobrunfeldt/concurrently#232]
Recently concurrently (on multiple projects) stopped working. I'm not aware of any changes to my setup that causes this to occur, as far as I'm aware everything was working fine then one day suddenly broke. 

I'm on windows 10, tested using CMD and PowerShell with the same results. Also tried updating node from 12.x.x to latest (14.4.0). Concurrently V5.2.0. 

All scripts run individually, but when run using concurrently they crash. 

Here's one script that I've tested, taken from the three.js repo:

``` json
"dev": "concurrently --names \"ROLLUP,HTTP\" -c \"bgBlue.bold,bgGreen.bold\" \"rollup -c utils/build/rollup.config.js -w -m inline\" \"http-server -c-1 -p 8080\"",
```

Here's the error message:

``` js
[ROLLUP] Error occurred when executing command: rollup -c utils/build/rollup.config.js -w -m inline
[ROLLUP] Error: spawn cmd.exe ENOENT
[ROLLUP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
[ROLLUP]     at onErrorNT (internal/child_process.js:468:16)
[ROLLUP]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[HTTP] Error occurred when executing command: http-server -c-1 -p 8080
[HTTP] Error: spawn cmd.exe ENOENT
[HTTP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
[HTTP]     at onErrorNT (internal/child_process.js:468:16)
[HTTP]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[HTTP] http-server -c-1 -p 8080 exited with code -4058
[ROLLUP] rollup -c utils/build/rollup.config.js -w -m inline exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! three@0.116.1 dev: `concurrently --names "ROLLUP,HTTP" -c "bgBlue.bold,bgGreen.bold" "rollup -c utils/build/rollup.config.js -w -m inline" "http-server -c-1 -p 8080"`
npm ERR! Exit status 1
```

Even if I remove all everything except `concurrently \"http-server -c-1 -p 8080\"` I get the same error.

**Comment by looeee** [comment]
On threads related to similar errors on StackOverflow, I've seen people recommend adding `C:\Windows\System32` to PATH. However, in my case this is already in PATH. 

I also found this post:
https://maximilianschmitt.me/posts/error-spawn-node-enoent-node-js-child-process/

**Comment by gustavohenke** [comment]
And have you updated concurrently itself lately?
Last release is from april, which has suspect changes: https://github.com/kimmobrunfeldt/concurrently/releases/tag/v5.2.0

**Comment by gustavohenke** [comment]
👆 that shouldn't cause any issues, from a quick look.

If you put your commands in `package.json`'s `scripts` like this:
```json
"scripts": {
  "server": "http-server -c-1 -p 8080"
}
```

and run it with `npm run server`, does it work?

**Comment by looeee** [comment]
> If you put your commands in package.json's scripts like this:

Yes, that works perfectly. Every script that I've tried works on it's own, they just don't work when using concurrently, even if it's just a single script.

**Comment by looeee** [comment]
Hmm, I just tried uninstalling and reinstalling node then restarting my system. Everything works now, on concurrently v5.2.0. 

I guess this was a node issue after all, although I have no idea what the problem was. Sorry for the trouble.

**Comment by gustavohenke** [comment]
No worries! Glad you fixed it.
Are you still on Node 14? concurrently on CI is only testing Node 12, maybe there's some breaking changes I'm not aware of.

**Comment by looeee** [comment]
I was on Node 12 when this first occurred. Upgraded to Node 14, no change. Then uninstalled completely and reinstalled Node 14 and that seemed to fix it.
