### ISSUE TITLE
Upgrade to lodash > 4.17.15

### ISSUE THREAD

**Issue by michaelyta** [kimmobrunfeldt/concurrently#237]
lodash versions 4.17.15 and below have a security vulnerability "Prototype pollution attack in zipObjectDeep".

Reference: https://github.com/lodash/lodash/issues/4744

**Comment by gustavohenke** [comment]
Updated dependency is on master branch already: 
https://github.com/kimmobrunfeldt/concurrently/compare/v5.2.0...master

I need to cut a new release though, some new features are included in it.

**Comment by gustavohenke** [comment]
Release as v5.3.0!

**Comment by Rahul-Bechtel** [comment]
lodash version 4.17.15 have  "Prototype pollution" vulnerability. lodash versions should be > 4.17.15 to remove security vulnerability.
