### ISSUE TITLE
Run clean up command before exit

### ISSUE THREAD

**Issue by ianpogi5** [kimmobrunfeldt/concurrently#240]
Would be great to have an option to run a command to do some cleanup. Example would be stopping a database docker container when you're done working.

**Comment by cben** [comment]
Straw man alternative: just run it after concurrently:
```
concurrently foo bar; cleanup
```
Do you want some different semantics?

**Comment by ianpogi5** [comment]
Thanks @cben! Don't know why I didn't think of that.
