### ISSUE TITLE
Add support to pass hex colors in prefixColor

### ISSUE THREAD

**Issue by rramaa** [kimmobrunfeldt/concurrently#260]
Hex colors are not currently supported as `prefixColor` value. However `chalk` package which is used internally has support for hex colors. It should be fixed by the following code?

```js
let color;
if(command.prefixColor.startsWith("#")) {
  color = chalk.hex(command.prefixColor)
} else {
  color = _.get(chalk, command.prefixColor, chalk.gray.dim);
}
```

Happy to open a PR!

**Comment by gustavohenke** [comment]
Out in v6.0.0!
