### ISSUE TITLE
Allow unlimited retries

### ISSUE THREAD

**Issue by flippidippi** [kimmobrunfeldt/concurrently#263]
For some tasks, unlimited retries would be nice instead of having to put a big number. Maybe allow -1 to indicate unlimited.

**Comment by mscottnelson** [comment]
Can’t you just specify the retries as the number Infinity? Even if you managed to get to the point where you lose precision or other odd behavior, your tries should still be definitionally less than Infinity

**Comment by gustavohenke** [comment]
I think that while it's certainly possible while via programmatic API, it may not be possible via CLI, so that's still a valid thing.

**Comment by gustavohenke** [comment]
feature is out in v6.2.0!
