### ISSUE TITLE
Extend Prefix with a Custom flag

### ISSUE THREAD

**Issue by Sicria** [kimmobrunfeldt/concurrently#27]
Is it possible to prefix each command? So instead of the command saying ``npm run app`` or ``npm run api`` it would just be ``app`` or ``api``.

Currently my command is like this.
```
"concurrently --timestamp-format 'YYYY-MM-DD HH:mm:ss' --prefix '[{time}] - [{index}]' --kill-others \"npm run start-dev:app\" \"npm run start-dev-api\""
```
With a result of this.
```
[2016-02-17 19:43:18] - [0] Connected to Database
[2016-02-17 19:43:18] - [1] Connected to API
```

Is it possible to do something like this?
```
"concurrently --timestamp-format 'YYYY-MM-DD HH:mm:ss' --prefix '[{time}] - [{custom}]' --custom 'APP,API' --kill-others \"npm run start-dev:app\" \"npm run start-dev-api\""
```
With a result of this.
```
[2016-02-17 19:43:18] - [API] Connected to Database
[2016-02-17 19:43:18] - [APP] Connected to API
```

**Comment by kimmobrunfeldt** [comment]
Not possible in the current implementation. That --custom CLI argument seems also quite decent to me, if someone does a PR with this I can merge it. Otherwise I can look into this later.

**Comment by OlsonDev** [comment]
I'm currently working on this and the ability to color the prefixes separately.

**Comment by kimmobrunfeldt** [comment]
Closing as this functionality is nowadays available thanks to @OlsonDev.
