### ISSUE TITLE
change default color gray.dim to reset

### ISSUE THREAD

**Issue by milahu** [kimmobrunfeldt/concurrently#275]
actual result: the default color `gray.dim` is very hard to read in a darkmode terminal

<img width="383" alt="concurrently default color gray dim Screenshot_20210507_173840" src="https://user-images.githubusercontent.com/12958815/117474402-286c4100-af5b-11eb-97dc-d4a67b5dca36.png">

expected result:

the default color should be `reset` = no color, no decorations, no bling bling ... just the default terminal style

if someone wants to change it, we should have the option `--default-color <color>`

more nitpick:
concurrently should wait for all processes to finish before doing process.exit()
when i hit control+C, i get my prompt `[user@nixos:...]`, but concurrently prints more output

**Comment by gustavohenke** [comment]
Color fix published in v6.1.0. Hopefully not a breaking change to anyone 😅 

--

About the other thing: if you could open different issues, that'd be great!
