### ISSUE TITLE
Flow controllers are not exported correctly

### ISSUE THREAD

**Issue by juona** [kimmobrunfeldt/concurrently#278]
The index file is supposed to export all the flow controllers at the end of the file:

```
// Export all flow controllers and the main concurrently function,
// so that 3rd-parties can use them however they want
exports.concurrently = concurrently;
exports.Logger = Logger;
exports.InputHandler = InputHandler;
```

This does not work because you have redefined `module.exports` and `exports` no longer references `module.exports`:

```
module.exports = (commands, options = {}) => { /*...*/ };

// This will not export anything
exports.Logger = Logger;
```

A simple fix is to use `module.exports` everywhere instead of `exports`.

**Comment by gustavohenke** [comment]
🤦 thanks for catching this!!
