### ISSUE TITLE
concurrent deprecated but still used in the README gif

### ISSUE THREAD

**Issue by grebett** [kimmobrunfeldt/concurrently#28]
Nice work for this update! Just in case you have not noticed it, the gif still uses the `concurrent` key-word.

**Comment by kimmobrunfeldt** [comment]
I thought to update it at somepoint and at least when the concurrent will be dropped. Thanks for the notice :) I'll leave this open until fixed.

**Comment by kimmobrunfeldt** [comment]
Fixed.
