### ISSUE TITLE
sh: 1: concurrently: Permission denied

### ISSUE THREAD

**Issue by RiazAhamed** [kimmobrunfeldt/concurrently#30]
I'm using `npm start` command node version 5.9.0 in my ubuntu os of Linux 3.13.0-79-generic, but always got this error.
**Error:**
> concurrently "npm run tsc:w" "npm run lite" 
sh: 1: concurrently: Permission denied

![bug](https://cloud.githubusercontent.com/assets/10165089/13898467/ae574d76-edf7-11e5-9840-797d2bbca20a.png)

[npm-debug.txt](https://github.com/kimmobrunfeldt/concurrently/files/180736/npm-debug.txt)

**Comment by kimmobrunfeldt** [comment]
What solved this issue?

**Comment by RiazAhamed** [comment]
I give executable premission to make my project folder and files in it recursively
`chmod -R <permissionsettings> <dirname>`
as a `<permissionsettings>` i give 777
and it works very well for me.

[For more help: How to set chmod for a folder and all of its subfolders and files in Linux Ubuntu Terminal?](http://stackoverflow.com/questions/3740152/how-to-set-chmod-for-a-folder-and-all-of-its-subfolders-and-files-in-linux-ubunt)

**Comment by almeidacavalcante** [comment]
RiazAhamed, works for me as well. Thank you.

**Comment by dwemerx** [comment]
Recently had the same issue. I didn't fix it specifically, but managed to solve my problem.

By running "concurrently yarn:lint:*", concurrently tries to execute all found files when it was ran by lint-staged which was executed by pre-commit husky hook. I fixed the problem by removing concurrently from lint-stage and adding all linting commands separately.

The following code doesn't work:

```
  "scripts": {
    "lint": "concurrently yarn:lint:*",
    "lint:pretty-quick": "pretty-quick --staged",
    "lint:eslint": "eslint src --ext .js,.jsx,.ts,.tsx",
  },
  "lint-staged": {
    "*.@(js|jsx|ts|tsx|md)": [
      "yarn lint"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }

```

And the following code works:

``` 
 "scripts": {
    "lint": "concurrently yarn:lint:*",
    "lint:pretty-quick": "pretty-quick --staged",
    "lint:eslint": "eslint src --ext .js,.jsx,.ts,.tsx",
  },
  "lint-staged": {
    "*.@(js|jsx|ts|tsx|md)": [
      "yarn lint:pretty-quick",
      "yarn lint:eslint"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }

```

Dependencies:
```
  "devDependencies": {
    "concurrently": "^5.3.0",
    "eslint": "^7.12.1",
    "husky": "^4.3.0",
    "lint-staged": "^10.5.0",
    "prettier": "^2.1.2",
    "pretty-quick": "^3.1.0",
  },

```

By the way, should this issues be re-open? Workaround with making affected files executable doesn't seem to be secure.
