### ISSUE TITLE
not compatible with nodejs devtool

### ISSUE THREAD

**Issue by matt1991** [kimmobrunfeldt/concurrently#32]
when debug using devtool, the output of concurrently is converted to plain string. I can't inspect the details inside an object using console.log. I tried to add option --raw. when doing this, all the output no longer redirects to the console of devtool

**Comment by MadLittleMods** [comment]
@matt1991 Try adding [`--raw`](https://github.com/kimmobrunfeldt/concurrently#usage)

Related to https://github.com/kimmobrunfeldt/concurrently/issues/23

**Comment by kimmobrunfeldt** [comment]
I haven't used devtool, if you mean this: https://github.com/Jam3/devtool. Could you provide a short example how to reproduce the bug? Which version of concurrently are you using?

**Comment by kimmobrunfeldt** [comment]
Inactive.
