### ISSUE TITLE
Running two servers only outputs information from one of them.

### ISSUE THREAD

**Issue by jakereps** [kimmobrunfeldt/concurrently#34]
I have a flask server backend for an express webpack-dev-server front-end and concurrently launching both works with `source activate venv && concurrently "server serve -d" "npm start"` (through an NPM script) as the front-end is correctly populating using the backend API points, BUT concurrently is only outputting the information from the express server to my terminal, and my flask backend hits aren't being displayed (i.e. all output is `[1] ... `, and there are no `[0] ...` logs). Is there a flag I'm missing, is this not possible, or is this a bug? 

---
##### edit
Strange. It appears to be working correctly if I use the built-in flask `app.run(...)`, but not with the `gevent.pywsgi.WSGIServer(...)` that the server is set up with...

---
##### edit May 31
Using `--raw` allows the flask server output to be displayed. Anyway to get this to work with the labels and colors?

**Comment by jakereps** [comment]
Strange. It appears to be working correctly if I use the built-in flask `app.run(...)`, but not with the `gevent.pyswgi.WSGIServer(...)` that the server is set up with...

**Comment by jakereps** [comment]
Found out this is actually a python issue where it knows when it is sharing a pipe and buffers any output. Putting a `-u` on the python command will let it run perfectly.

**Comment by karlhorky** [comment]
Nice find, was trying to debug this issue today.

Another way that I found to disable the buffering is to set [the `PYTHONUNBUFFERED` environment variable](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED) to a non-empty string.
