### ISSUE TITLE
npm run doesn't forward signals to processes

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/concurrently#4]
--kill-others option is useless if "npm run task" is used because of this issue: https://github.com/npm/npm/issues/4603

**Comment by jeffbski** [comment]
+1

**Comment by louy2** [comment]
+1

**Comment by kimmobrunfeldt** [comment]
Nothing we can do about this. NPM officially states: 

> That said, and taking into account everybody's feedback, I'm going to close this feature request now, because this isn't something that the team is going to have time to get to in the next 6-12 months. npm start / npm stop / npm restart are handy and convenient, but they're not substitutes for a dedicated process manager. If somebody wants to submit a patch that handles this behavior for both UNIXy systems and Windows, we'll land it, but the team isn't going to do it themselves. Thanks to everybody for their feedback!

**Comment by dsernst** [comment]
A fix for this [landed in npm@3.8.1](https://github.com/npm/npm/pull/10868#issuecomment-192457737)

**Comment by kimmobrunfeldt** [comment]
Nice!! Thanks for reporting

**Comment by dchambers** [comment]
I've asked a [question about Linux support](https://github.com/npm/npm/pull/10868#issuecomment-217124265) on the upstream issue since this fix doesn't appear to be working for me on Linux right now.
