### ISSUE TITLE
Run npm scripts instead of commands

### ISSUE THREAD

**Issue by remcohaszing** [kimmobrunfeldt/concurrently#46]
I think it would be useful if one could enable _npm mode_ by adding `--npm`. This would take all commands passed to concurrently, and change it to `npm run <command>`. Additionally this could set the names to the npm script name. For example:

```
concurrently --names eslint,htmlhint,stylelint,karma,protractor,conventional-changelog-lint -p name 'npm run eslint' 'npm run htmlhint' 'npm run stylelint' 'npm run karma' 'npm run protractor' 'npm run conventional-changelog-lint'
```

could be rewritten as:

```
concurrently --npm eslint htmlhint stylelint karma protractor conventional-changelog-lint
```

Especially when used in `package.json` this would be much less cluttered. E.g.:

``` json
  "scripts": {
    "test": "concurrently --names eslint,htmlhint,stylelint,karma,protractor,conventional-changelog-lint -p name 'npm run eslint' 'npm run htmlhint' 'npm run stylelint' 'npm run karma' 'npm run protractor' 'npm run conventional-changelog-lint'",
    "conventional-changelog-lint": "conventional-changelog-lint --from HEAD~1",
    "eslint": "eslint --color .",
    "htmlhint": "htmlhint --config .htmlhintrc src/**/*.html",
    "karma": "karma start --colors --single-run karma-jenkins.conf.js",
    "protractor": "protractor",
    "stylelint": "stylelint ."
  },
```

would become:

``` json
  "scripts": {
    "test": "concurrently --npm eslint htmlhint stylelint karma protractor conventional-changelog-lint",
    "conventional-changelog-lint": "conventional-changelog-lint --from HEAD~1",
    "eslint": "eslint --color .",
    "htmlhint": "htmlhint --config .htmlhintrc src/**/*.html",
    "karma": "karma start --colors --single-run karma-jenkins.conf.js",
    "protractor": "protractor",
    "stylelint": "stylelint ."
  },
```

**Comment by carusology** [comment]
This is how I organize my concurrently-ran scripts as well, though I think any solution here should be forward thinking in how to support passing arguments to any given npm script.

**Comment by kimmobrunfeldt** [comment]
I like the idea, but I'm not sure if concurrently would be the best place to build this functionality. Open to hear others' comments.

**Comment by replete** [comment]
+1

`concurrently` has become the standard for npm scripts-as-task-runner scenarios.

This feature would considerably simplify messes like this:
`"watch": "concurrently -p \"npm run html-watch\" \"npm run css-watch\" \"npm run serve\"",`

`"watch" : "concurrently --npm html-watch css-watch serve"` would be great.

**Comment by JuanCaicedo** [comment]
I think @kimmobrunfeldt's thought is that `concurrently` shouldn't be node specific in usage? I agree with that, but I also think it could be possible to get the benefits of both. [GNU parallel](https://www.gnu.org/software/parallel/) uses a syntax like 

```bash
parallel npm ::: task-1 task-2
```

Maybe what `concurrently` could do is something like

```bash
concurrently --command "npm run" -p task-1 task-2
```

`--command` isn't a very good name, open to suggestions 😄

**Comment by xaviergonz** [comment]
I recently made a tool to make running parallel npm-scripts easier (among other things) - https://www.npmjs.com/package/makfy
Hope it is useful to any of you.

**Comment by remcohaszing** [comment]
I've switched to [npm-run-all](https://www.npmjs.com/package/npm-run-all) instead. It basically does what this issue describes.

**Comment by pgraham** [comment]
I, like @remcohaszing recohaszing tried [npm-run-all](https://github.com/mysticatea/npm-run-all) but found that it is not as robust at handling output &mdash; the Rollup.js watch command in particular tripped it up.

My suggestion for supporting this feature, but still allowing non-npm commands, is to support a`npm:cmd` format for individual command that is translated to `npm run cmd`:

```bash
$ concurrently "npm:watch-node" "npm:watch-js" "npm:watch-css"
```
would be equivalent to:

```bash
$concurrently -n "watch-node,watch-js,watch-css" "npm run watch-node" "npm run watch-js" "npm run watch-css"
```

**Comment by shtanton** [comment]
When I try to use this feature, I get:

`yarn run v1.1.0`
`$ concurrently 'npm:dev-bsb' 'npm:dev-babel'`
`[0] /bin/sh: npm:dev-bsb: command not found`
`[1] /bin/sh: npm:dev-babel: command not found`
`[1] npm:dev-babel exited with code 127`
`[0] npm:dev-bsb exited with code 127`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by gustavohenke** [comment]
It isn't released yet @shtanton

**Comment by gustavohenke** [comment]
Well, that's now possible since v3.6.0, thanks to amazing efforts by @pgraham!

`concurrently npm:watch-js npm:watch-css npm:server`
