### ISSUE TITLE
Request: restart process

### ISSUE THREAD

**Issue by danfma** [kimmobrunfeldt/concurrently#48]
Hey guys,

It would be nice if the concurrently could restart a process which died. This would allow in some cases, when you use build tasks or launch processes that could die but can be restored.
# Propose
- Add a --allow-restart flag to allow this behavior;
- Add a --restart-after XXX flag to set a delay time to respawn the process;
- Add a --restart-tries XXX flag to limit the number of respawn tries.

**Comment by kimmobrunfeldt** [comment]
I agree this could be useful. I'm open to a PR for this.

**Comment by gcca** [comment]
Currently someone is working on this feature. I open a PR for this.

**Comment by gustavohenke** [comment]
Implemented by #100
