### ISSUE TITLE
3.3.0 fails to run commands on Windows 10

### ISSUE THREAD

**Issue by Iankodj** [kimmobrunfeldt/concurrently#63]
The problem was reproduced while trying out the quick-start Angular 2 app. With concurrently 2.2.0 everything runs fine. 

Details:

```
$ concurrently --kill-others "npm run tsc:w" "npm run lite"
[1] /c: /c: is a directory
[0] /c: /c: is a directory
[0] npm run tsc:w exited with code 126
[1] npm run lite exited with code 126
```

```
$ npm -v
3.10.8
```

```
$ node -v
v6.7.0
```

**Comment by kimmobrunfeldt** [comment]
Thanks for reporting. This seems to be the same issue as https://github.com/kimmobrunfeldt/concurrently/issues/60. Let's continue the discussion there.
