### ISSUE TITLE
It's sometimes useful to delay the start of one of the processes

### ISSUE THREAD

**Issue by dchambers** [kimmobrunfeldt/concurrently#65]
I've needed this a couple of times when I've started a server in one of the processes, and some app that expects that server to be immediately available in the other process. I've been able to solve this problem by making use of the [wait-on](https://www.npmjs.com/package/wait-on) package, as follows:

```
"start": "concurrently -k -s first \"npm run server\" \"npm run app\"",
"server": "node server.js",
"app": "wait-on http://localhost:3000/ && node app.js"
```

I'm just creating this issue to help other people that hit the same issue.

**Comment by kimmobrunfeldt** [comment]
Thanks for sharing!

**Comment by jcrben** [comment]
This is such a complementary feature. I suggest adding this suggestion to the readme.

I also think that a tool which can handle both makes sense.

**Comment by joshuapinter** [comment]
@dchambers Thanks for sharing this! Exactly what I needed and saved me time looking for a solution. 🙏

**Comment by MonrealRyan** [comment]
@dchambers thanks for this. it helps me a lot. cheers
