### ISSUE TITLE
Cancel concurrently tasks leave running processes even with `--kill-others`

### ISSUE THREAD

**Issue by NonPolynomial** [kimmobrunfeldt/concurrently#67]
Hey there,

when i run conccurrently and then cancel it with ctrl+c, there are running tasks.
Is there a concurrently `cleanup` or something like that?

---

My package.json:

``` json
{
  "name": "playground",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "yarn run build:js && yarn run build:css",
    "build:css": "node-sass --source-map-embed --output-style compressed --recursive src/scss/style.scss > dist/css/combined.min.css",
    "build:js": "babel src/js/ --minified -o dist/js/combined.min.js",
    "dev:js": "babel src/js/ -o dist/js/combined.js",
    "dev:css": "node-sass --source-map-embed --output-style expanded --recursive src/scss/ --output dist/css/",
    "watch": "concurrently --kill-others \"yarn run dev:css -- --watch\" \"yarn run dev:js -- --watch\""
  },
  "dependencies": {
    "babel-cli": "^6.16.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-es2015-modules-umd": "^6.12.0",
    "babel-preset-es2015": "^6.16.0",
    "concurrently": "^3.1.0",
    "node-sass": "^3.10.1"
  }
}
```

running those tasks with `npm`instead of `yarn` results in the same issue.

**Comment by kimmobrunfeldt** [comment]
Which version of NPM are you using? Have you seen this issue https://github.com/kimmobrunfeldt/concurrently/issues/4

**Comment by NonPolynomial** [comment]
hey hier is my `npm version` output:

```json
{
  npm: '3.10.6',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8'
}
```

OS: I noticed this bug on Win7, Win8.1 and Win10.

**Comment by jonaskello** [comment]
I have the same problem on Windows 10. Tried both yarn 0.18.0 and npm 3.10.9.

**Comment by filipesilva** [comment]
I think I'm getting this, but not on when using CMD. Only when using gitbash (mingw).

**Comment by NonPolynomial** [comment]
> I think I'm getting this, but not on when using CMD. Only when using gitbash (mingw).

Strange.. I tried it with cmd, powershell, mingw and mingw inside powershell, but tasgmanager said, the watch task ist runnning, even after break (ctrl + c)...

I need to check it again

**Comment by gustavohenke** [comment]
Published [v3.2.0](https://github.com/kimmobrunfeldt/concurrently/releases/tag/3.2.0)!

**Comment by filipesilva** [comment]
Awesome, thanks @gustavohenke

**Comment by NonPolynomial** [comment]
Sorry for my late response!
I tried v3.5.0 and it seems to be fixed.

Thanks!

**Comment by JoshMoxey** [comment]
I'm using concurrently v3.5.1 & gitbash (MINGW) on Windows 10. After trying to cancel w/ ctrl + c, it appears to cancel, but then when I make any file changes there's still output from nodemon/react hot reload. 

PS, I'm new to reporting bugs, so bare with me. :)

**Comment by stereokai** [comment]
Also happening to me, latest version, npm 3, Win 10

**Comment by ilearnio** [comment]
Same here. Ctrl+c exits but the process is still ongoing. Even everything I have after `&&` runs after concurrently finishes

**Comment by joshbedo** [comment]
Having this issue too
