### ISSUE TITLE
spawn-default-shell problem on 3.1.0

### ISSUE THREAD

**Issue by vhpoet** [kimmobrunfeldt/concurrently#71]
I'm getting `Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.` on Centos after upgrading to `concurrently#3.1.0`. The result of `echo $SHELL` is `/bin/bash`.

**Comment by kimmobrunfeldt** [comment]
Can you try manually setting `export SHELL_EXECUTE_FLAG=-l -c` ? Sounds like a bug if the flags are not decided based on the shell

**Comment by vhpoet** [comment]
weirdly it works after setting `SHELL=/bin/bash`, must be a systemd service thing. Closing the issue for now, thanks!
