### ISSUE TITLE
Minimum version?

### ISSUE THREAD

**Issue by JuanCaicedo** [kimmobrunfeldt/concurrently#76]
Is there a minimum supported node version for this tool? If support was dropped node < v4, it would be possible to leverage some great ES6 features like [template literals](https://jack.ofspades.com/multiline-strings-in-es6-javascript/)!

I think it's possible to enforce this through "engines" in [package.json](https://docs.npmjs.com/files/package.json#engines)

**Comment by JuanCaicedo** [comment]
Also, the build is [currently failing](https://travis-ci.org/kimmobrunfeldt/concurrently/jobs/189572783) because it is testing node v0.12, which doesn't support arrow functions, which are used in `test/test-functional.js`

**Comment by gustavohenke** [comment]
I fixed the problem of node 0.12 tests with #83.

Also, as stated in the npm docs link you posted, `engines` will not really "enforce" anything by default, it'll only warn you that you're using incorrect node version:

> Note that, unless the user has set the `engine-strict` config flag, this field is advisory only.`

Anyway, I'll add this flag to our `package.json`.
