### ISSUE TITLE
Test code not testing src?

### ISSUE THREAD

**Issue by JuanCaicedo** [kimmobrunfeldt/concurrently#78]
Hi there, I'm digging in trying to understand this code and thought I would try to understand the tests to start. I looked [test/test-functional.js](https://github.com/kimmobrunfeldt/concurrently/blob/master/test/test-functional.js) and found that it is testing a function `run` defined in [test/utils.js](https://github.com/kimmobrunfeldt/concurrently/blob/master/test/utils.js).

I just want to make sure I'm not confused, but does that mean these tests aren't executing the source code at all? I feel like they should be

**Comment by gustavohenke** [comment]
Hi @JuanCaicedo!
Our tests are indeed using this function called `run`, but it's just a wrapper to use some defaults when dealing with the `child_process` module. Every test spawns `src/main.js` passing different CLI args, eg:

```js
return run('node ./src/main.js "echo test" "nosuchcmd" "echo test"')...
```
