### ISSUE TITLE
--kill-others not working properly

### ISSUE THREAD

**Issue by HansHammel** [kimmobrunfeldt/concurrently#80]
I am on windows 10 nodev 6.9.1

Something is wrong with the process termination. I have checked my exit codes, and tried a simple setInterval example, but the server process exits with code 0 when killed with ctrl+c (SIGINT) and exit code 1 from within concurrently. 

here is the simplifier code to reproduce it

client.js
```js
setTimeout(function(){process.exit(0);},2000);
```
server.js
```js
    process.on('SIGTERM', function() {
        console.log('SIGTERM - Server closing...');
        process.exit(0);
    });
    process.on('SIGHUP', function() {
        console.log('SIGHUP - Server closing...');
        process.exit(0);
    });

    process.on('SIGINT', function() {
        console.log('SIGINT - Server closing...');
        process.exit(0);
    });
    process.on('exit', function() {
        console.log('EXIT - Server closing...');
        process.exit(0);
    });



    console.log('Server started, listening on port 4545');
    setInterval(function(){},1000);
```

![image](https://cloud.githubusercontent.com/assets/6475700/21753017/79363402-d5e3-11e6-9381-33dcb3dac494.png)

One more weird thing, without --kill-others, the exit code on crtl+c is null
![image](https://cloud.githubusercontent.com/assets/6475700/21753141/7d7370ea-d5e6-11e6-9dcf-b5abc7bc95d3.png)

**Comment by gustavohenke** [comment]
Hi @HansHammel! Have you tried using concurrently@v3.3.0?
We changed the underlying dependency used to spawn commands.

Using it, the process exited with `0` on <kbd>Ctrl</kbd> + <kbd>C</kbd> (I tried the same code as you on my Windows 10 system).

Regarding `SIGTERM` and Windows, v3.3.0 got exit code `1` too 😢

**Comment by karimsa** [comment]
I can reproduce.

I am using concurrently on Linux x64 (via Travis CI) and on my local machine (macOS Sierra). Both are running **node v7.7** with concurrently (`3.4.0` - though I also tested with `3.3.0` after reading this thread). It seems that if one of the two processes fail or one exits (and the other receives `SIGTERM`), concurrently exits with code `null` (not sure how?) and this causes my build to fail.

Here is my build: [https://travis-ci.org/karimsa/delish/builds/213052516](https://travis-ci.org/karimsa/delish/builds/213052516)

**Comment by gustavohenke** [comment]
Hi @karimsa!
[Node exits with `null` code when it receives `SIGTERM`/`SIGKILL`, etc](https://nodejs.org/api/child_process.html#child_process_event_exit).
AFAIK, there's nothing we can do about it.

Therefore, concurrently will exit with code `1`, as one of your processes exited without success.
You can control this behavior with the (rather limited) `--success` flag.

**Comment by gustavohenke** [comment]
(which has just been released, of course).
