### ISSUE TITLE
Error when running on CI: `stdin: is not a tty`

### ISSUE THREAD

**Issue by Maistho** [kimmobrunfeldt/concurrently#88]
When using concurrently on Gitlab CI I get the following error:

```
[0] stdin: is not a tty
[0] /bin/sh: 1: ng: not found
```

This error did not appear before 3.2.0. Maybe it has to do with updating spawn-default-shell?

**Comment by gustavohenke** [comment]
Yeah, it seems like a problem with the upgrade:  https://gitlab.com/gustavohenke/test2/builds/10175508#down-build-trace

**Comment by gustavohenke** [comment]
Do you have more details on the second error? How should I could reproduce it?

**Comment by Maistho** [comment]
I think the second error is because I try to run angular-cli (ng) which is
installed locally. It could be dependent on the first error. I can make a
public repo in an hour or so to reproduce.

**Comment by gustavohenke** [comment]
Published [v3.3.0](https://github.com/kimmobrunfeldt/concurrently/releases/tag/3.3.0).
Can you try it, @Maistho?

**Comment by Maistho** [comment]
Seems to work as it should! =)
