### ISSUE TITLE
Invalid PATH when running with mingw

### ISSUE THREAD

**Issue by ilivit** [kimmobrunfeldt/concurrently#90]
After updating from 3.1.0 to 3.2.0 I can't run npm concurrently in git-bash.

For example I have script in package.json: `"dev": "concurrently \"npm run tsc:w\" \"node sync.js\" "` and run it with `$npm run dev`. But with 3.2.0 I'm getting that:

    $ npm run dev:r
    > concurrently "npm run tsc:w" "node sync.js"
    
    [1] /usr/bin/bash: node: command not found
    [1] node sync.js exited with code 127
    [0] /usr/bin/bash: npm: command not found
    [0] npm run tsc:w exited with code 127
    
    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev:r"
    npm ERR! node v7.4.0
    npm ERR! npm  v4.0.5
    npm ERR! code ELIFECYCLE
    npm ERR! test@1.0.0 dev:r: `concurrently "npm run tsc:w" "node sync.js" `
    npm ERR! Exit status 1
    ...

Though it works fine in cmd.
Here's also the log files produced by node: [debug.log.txt](https://github.com/kimmobrunfeldt/concurrently/files/766527/debug.log.txt), [npm-debug.log.txt](https://github.com/kimmobrunfeldt/concurrently/files/766528/npm-debug.log.txt).
And here's the output of `echo $PATH` and `concurrent 'echo $PATH'`: [echo.txt](https://github.com/kimmobrunfeldt/concurrently/files/766545/echo.txt).
It seems that concurrently's PATH has been messed up.

**Comment by hakatashi** [comment]
I also have the same PATH issue when running scripts in Travis-CI after upgrading concurrently 3.1.0 to 3.2.0.

Since Travis uses nvm's PATH system to control node version, this break version management in Travis-CI using concurrently module.

* related issue: https://github.com/tsg-ut/mnemo/pull/230
* `echo $PATH` in npm script: https://travis-ci.org/tsg-ut/mnemo/builds/200683019#L1462
* `echo $PATH` in concurrently in npm script: https://travis-ci.org/tsg-ut/mnemo/builds/200683019#L1520

**Comment by gustavohenke** [comment]
Published [v3.3.0](https://github.com/kimmobrunfeldt/concurrently/releases/tag/3.3.0).
Can you guys try it?

**Comment by hakatashi** [comment]
[It seems to work quite well.](https://github.com/tsg-ut/mnemo/pull/232) Thank you!

**Comment by ilivit** [comment]
It seems that `spawn-command` always uses `cmd.exe` when running on windows. 
I've created a PR (https://github.com/mmalecki/spawn-command/pull/7) to fix that.

**Comment by gustavohenke** [comment]
What's your reason to want that?

Talking about features, I would always prefer spawn-default-shell over spawn-command.
But I'm having a hard time to accept that we'll have fewer headaches in the long run by sticking to a simpler dependency like spawn-command.

**Comment by ilivit** [comment]
I'm running npm and node from git-bash shell, so I would prefer to run all processes started by them within one environment. Messing up the shells could introduce new bugs and glitches like an encoding inconsistency.
