### ISSUE TITLE
exit code `null` when --kill-others specified

### ISSUE THREAD

**Issue by kentcdodds** [kimmobrunfeldt/concurrently#91]
This one's a little odd, but occasionally (not always), concurrently will receive an exit code of `null` from one of the processes when I specify `--kill-others` (like [here](https://travis-ci.org/kentcdodds/nps/builds/202870835)).

This may be related to #37 and #80 which also indicate an exit code of `null`. Anyone know how that could happen? And better yet, how to fix it? [Here's the code](https://github.com/kimmobrunfeldt/concurrently/blob/master/src/main.js#L272) where the exit code comes from.

For now, the workaround is to not use `--kill-others`, but that's kinda annoying... :-/ I'm happy to submit a fix if someone can give me an idea of how this is even possible.

**Comment by Wildhoney** [comment]
Was there a resolution @kentcdodds?

I get the same issue when running a node.js app (even when the node.js app is an empty file) and **any** other command, such as an `echo`:

```bash
concurrently -k 'node app.js' 'echo "hello world"'
```

If I replace the `node app.js` with anything else such as `echo` then the exit code is `0`.

However with `node` I receive an exit code of `null`:

> [1] echo "..." exited with code 0
> --> Sending SIGTERM to other processes..
> [0] npm run start exited with code null

**Comment by kentcdodds** [comment]
Well, I opened a PR to fix it and it was merged/released. Maybe what you're seeing is unrelated to what I experienced. You may need to dig deeper.
