### ISSUE TITLE
add --max-concurrent

### ISSUE THREAD

**Issue by kentcdodds** [kimmobrunfeldt/concurrently#96]
I may have several things I can run in parallel, but I may want to only run 5 of them at a time. I'd love to be able to specify how many to run at once with `--max-concurrent`. Thoughts?

**Comment by gustavohenke** [comment]
Why not? 😃

**Comment by maxogden** [comment]
I also would like this feature! This module would make it pretty easy to implement: https://www.npmjs.com/package/run-parallel-limit

**Comment by kentcdodds** [comment]
Thanks @maxogden. Someone correct me if I'm wrong, but because this project is using RxJS, this actually should be fairly straightforward to implement with just RxJS.

**Comment by sandinmyjoints** [comment]
There's also https://www.npmjs.com/package/parallel, a JS implementation of GNU parallel, which allows setting a max number of processes to run.

**Comment by kentcdodds** [comment]
Good as a reference maybe. Concurrently has a bunch of really nice features that I enjoy (like colored labels) :smile:

**Comment by jseminck** [comment]
If this one is still up for grabs, then I'd like to take a look!

**Comment by gustavohenke** [comment]
@jseminck sure, go ahead!

**Comment by kentcdodds** [comment]
I'm trying to clean up my issues, so I'm going to go ahead and close this. If I need this again I'll reopen this (or you can reopen if you'd like).
